### Import Libraries

In [1]:
import tensorflow as tf
import numpy as np

### Load Data

In [2]:
mnist = tf.keras.datasets.mnist

test = mnist.load_data()

(x_train, y_train), (x_test, y_test) = mnist.load_data()

#Divide by 255, to get values of 0 to 1
x_train, x_test = x_train / 255.0, x_test / 255.0

### Create Model

In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

### Stats Before

In [4]:
#Predictions Before
predictions = model.predict(x_train[:1])
predictions

array([[-0.39104348,  0.01267524,  0.24787042, -0.5621866 ,  0.14556156,
        -0.26154554, -0.60803914,  0.8961331 ,  0.112286  ,  0.39118344]],
      dtype=float32)

In [5]:
#Softmax Function to convert into probabilites
tf.nn.softmax(predictions).numpy()

array([[0.06115839, 0.09157752, 0.11585981, 0.05153824, 0.10459253,
        0.06961396, 0.04922843, 0.22154897, 0.10116942, 0.13371277]],
      dtype=float32)

In [6]:
#Loss Before
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True)
loss_fn(y_train[0], predictions).numpy()

2.6647902

### Train and Evaluate Model

In [7]:
#Train Model
model.compile(optimizer="adam",
              loss=loss_fn,
              metrics=["accuracy"])

model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 67s 36ms/step - loss: 0.2934 - accuracy: 0.9154
Epoch 2/5
1875/1875 [==============================] - 53s 28ms/step - loss: 0.1435 - accuracy: 0.9568
Epoch 3/5
1875/1875 [==============================] - 32s 17ms/step - loss: 0.1076 - accuracy: 0.9675
Epoch 4/5
1875/1875 [==============================] - 30s 16ms/step - loss: 0.0895 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 28s 15ms/step - loss: 0.0764 - accuracy: 0.9763


In [8]:
model.evaluate(x_test, y_test)

313/313 [==============================] - 3s 9ms/step - loss: 0.0737 - accuracy: 0.9778


[0.07367298752069473, 0.9778000116348267]

In [9]:
probability_model = tf.keras.models.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [10]:
probability_model.predict(x_test[:5])

array([[8.88635920e-09, 6.07069228e-10, 1.66024279e-06, 5.71821038e-05,
        9.34997774e-11, 1.17134235e-07, 1.15922910e-13, 9.99938369e-01,
        5.93806419e-07, 2.04808020e-06],
       [4.88931391e-07, 2.64810340e-04, 9.99690413e-01, 3.75210766e-05,
        2.48415604e-14, 4.56808721e-06, 1.13236922e-07, 6.85858922e-12,
        2.17000570e-06, 3.65808859e-12],
       [1.01177091e-06, 9.98231351e-01, 4.24099781e-05, 6.09053859e-06,
        4.51527740e-05, 2.52455920e-05, 2.41345275e-04, 6.49827358e-04,
        7.57024507e-04, 5.76885668e-07],
       [9.99683022e-01, 2.68747441e-10, 9.69968751e-05, 6.85422350e-08,
        1.14908380e-06, 7.34985292e-07, 5.27016209e-06, 1.83843193e-04,
        1.80084982e-07, 2.86413942e-05],
       [1.47040279e-04, 1.95503155e-10, 9.14110785e-07, 3.91394224e-08,
        9.84809458e-01, 2.38043913e-06, 2.87066496e-06, 1.01842976e-04,
        1.76727553e-06, 1.49336904e-02]], dtype=float32)

### Stats After

In [11]:
#Predictions After
predictions = model.predict(x_train[:1])
predictions

array([[-10.34595  ,  -8.515127 ,  -2.4987988,   5.816771 , -28.521261 ,
         12.110149 , -14.636254 ,  -6.618055 ,  -8.620899 ,  -1.4439933]],
      dtype=float32)

In [12]:
#Softmax Function to convert into probabilites
tf.nn.softmax(predictions).numpy()

array([[1.7645610e-10, 1.1009139e-09, 4.5145219e-07, 1.8450907e-03,
        2.2552806e-18, 9.9815315e-01, 2.4175867e-12, 7.3390729e-09,
        9.9041497e-10, 1.2963064e-06]], dtype=float32)

In [13]:
#Loss After
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[0], predictions).numpy()

0.0018485378